#server:
#  port: 8088
#  address: localhost
#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://121.199.38.85:3306/d_wdt2a_v2
#    username: dev
#    password: wdterp
#  application:
#    name: test
spring:
  profiles:
    active: dev
nacos:
  config:
    type: yaml
    server-addr: 127.0.0.1:8848
    context-path: nacos
    data-ids: test_dev,dev_value
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log:
        enable: true
    namespace: 9f0913b6-6eae-4195-b609-0eceb3a3910f